--- 
- name: Collect set of facts in PowerScale
  hosts: localhost
  connection: local
  vars:
    onefs_host: '192.168.1.150'
    verify_ssl: false
    api_user: 'root'
    api_password: 'Password123!'
    access_zone: 'System'
    include_all_access_zones: true

  tasks:
    - name: Get attributes, access_zones and nodes of the PowerScale cluster
      dellemc.powerscale.info:
        onefs_host: "192.168.1.150"
        verify_ssl: "false"
        api_user: "root"
        api_password: "Password123!"
        gather_subset:
          - attributes
          - access_zones
          - nodes