---
- name: SMB Global Settings Module Operations on PowerScale Storage
  hosts: localhost
  connection: local
  vars:
    onefs_host: "10.**.**.**"
    port_no: "1234"
    api_user: "user"
    api_password: "password"
    verify_ssl: false

  tasks:
    - name: Get SMB global settings
      dellemc.powerscale.smb_global_settings:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ port_no }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"

    - name: Update SMB global settings
      dellemc.powerscale.smb_global_settings:
        onefs_host: "{{ onefs_host }}"
        port_no: "{{ port_no }}"
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        verify_ssl: "{{ verify_ssl }}"
        access_based_share_enum: true
        dot_snap_accessible_child: true
        dot_snap_accessible_root: false
        dot_snap_visible_child: false
        dot_snap_visible_root: true
        enable_security_signatures: true
        guest_user: user
        ignore_eas: false
        onefs_cpu_multiplier: 2
        onefs_num_workers: 4
        reject_unencrypted_access: true
        require_security_signatures: true
        server_side_copy: true
        server_string: 'PowerScale Server'
        service: false
        support_multichannel: true
        support_netbios: true
        support_smb2: true
        support_smb3_encryption: false
